import React, { useState } from 'react';
import api from '../services/api';
import { useSeo } from '../hooks/useSeo';

export default function ReportsPage() {
  useSeo({
    title: 'Reports',
    description: 'Download Smart Library reports as PDF or Excel exports.',
  });
  const [loading, setLoading] = useState('');
  const [error, setError] = useState('');

  const downloadReport = async (type) => {
    setLoading(type);
    setError('');
    const extension = type === 'pdf' ? 'pdf' : 'xlsx';
    const mime = type === 'pdf' ? 'application/pdf' : 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
    try {
      const { data } = await api.get(`/util/reports/books.${extension}`, { responseType: 'blob' });
      const url = window.URL.createObjectURL(new Blob([data], { type: mime }));
      const link = document.createElement('a');
      link.href = url;
      link.download = `book-report.${extension}`;
      link.click();
      window.URL.revokeObjectURL(url);
    } catch (err) {
      console.error(err);
      setError('Unable to download report. Please confirm the backend is running and you are signed in.');
    } finally {
      setLoading('');
    }
  };

  return (
    <div className="space-y-6">
      <section className="page-card p-6 sm:p-8">
        <p className="section-label">Reporting</p>
        <h2 className="mt-4 text-3xl font-semibold text-white">Authenticated exports</h2>
        <p className="mt-3 max-w-3xl leading-7 text-slate-400">Download professional PDFs and spreadsheet exports through the secured backend for inventory, audits, and management reviews.</p>
      </section>

      {error && <div className="rounded-3xl border border-red-400/20 bg-red-500/10 px-4 py-3 text-sm text-red-200">{error}</div>}

      <div className="grid gap-4 md:grid-cols-2">
        <button className="page-card p-5 text-left transition hover:bg-white/10" onClick={() => downloadReport('pdf')} disabled={Boolean(loading)}>
          <div className="font-medium text-white">{loading === 'pdf' ? 'Preparing PDF...' : 'Download Book Report PDF'}</div>
          <div className="mt-2 text-sm text-slate-400">Professional PDF export generated by Spring Boot.</div>
        </button>
        <button className="page-card p-5 text-left transition hover:bg-white/10" onClick={() => downloadReport('excel')} disabled={Boolean(loading)}>
          <div className="font-medium text-white">{loading === 'excel' ? 'Preparing Excel...' : 'Download Book Report Excel'}</div>
          <div className="mt-2 text-sm text-slate-400">Spreadsheet export for analytics and inventory.</div>
        </button>
      </div>
    </div>
  );
}
