spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:mysql}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:smart_library}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:smartlib}
    password: ${MYSQL_PASSWORD:smartlib123}
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: update